### ISSUE TITLE
Previously filed issues

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc.github.io#1]
@brianking I have filed some issues before. Where did they go?

**Comment by brianking** [comment]
@berezovskyi  I don't know. What were the issues about? Were they website related? Did you put them in the issues section of another repository here?

**Comment by berezovskyi** [comment]
I was only able to find it in my profile log:

![image](https://user-images.githubusercontent.com/64734/27580717-d304d93e-5b2b-11e7-803d-3eb02ba64a7c.png)

Let's see what happens when you reopen the issues in the hugo repo as discussed in #2

**Comment by brianking** [comment]
Ok I re-enabled issues on the other repo and found them. They are back at:

https://github.com/OSLC/oslc-site-hugo/issues
