### ISSUE TITLE
Move issues to the hugo repo

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc.github.io#2]
I think this repo is deploy-only, so you should forbid pull requests on this repo, but instead open issues in the hugo repo. Because in the issue I might want to point to the deploy script or in the pull request reference an issue.

@brianking

**Comment by brianking** [comment]
@berezovskyi Yes indeed, I agree with you. I'll go ahead and make the changes.

**Comment by brianking** [comment]
@berezovskyi I don't know how to disable pull requests on a repository, do you?

**Comment by berezovskyi** [comment]
Sadly, this is how GH forces "collaboration". An equally brutal solution: https://nopullrequests.appspot.com/

**Comment by brianking** [comment]
I think for now we can just close them manually.
